apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-nlb8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-nlb8
    app.kubernetes.io/part-of: tkrw-pr712-0075-0002-app
  name: devfile-sample-nlb8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-nlb8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-nlb8
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0002-tenant/tkrw-pr712-0075-0002-app/devfile-sample-nlb8@sha256:8a979cdcef26acf2be26b912ddbf81fde7d66848ef84cd27aceaccda4e44077f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
